name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run test
        uses: ./
        with:
          roblox_api_key: ${{ secrets.ROBLOX_API_KEY }}
          universe_id: ${{ vars.ROBLOX_UNIVERSE_ID}}
          place_id: ${{ vars.ROBLOX_PLACE_ID}}
          luau_file: 'tests/workflow/main.luau'
          dump_to_summary: true
